### ISSUE TITLE
vagrant provision

### ISSUE THREAD

**Issue by penguin02007** [ppouliot/ansible-drbd_virt_cluster#8]
Please update Readme on how to stand up the cluster - via vagrant provision or ansible-playbook.
```
$ vagrant provision
 [WARNING]: Could not match supplied host pattern, ignoring: drbd-cluster
```

**Comment by ppouliot** [comment]
How to stand up the cluster is documented in the read me.     Please read all the included urls in the read me for information on standing up this cluster.  Vagrant is incapable of deploying the entire cluster due to its limitations, it is only there as an attempt to try to validate some of the parts of the deployment.    Please read the read me to see the goals of this project.
